In [1]:
import pandas as pd
import re
df = pd.read_excel(r"C:\Users\Vanessa\Downloads\Dados\Programas\Repositório Git\NGO_DataAnalysis\excel_exemplo.xls", usecols = [0, 1, 2, 4, 5, 7], index_col = None)
df

,Balancete Mensal - OBA - ORGANIZAÇÃO BEM-ANIMAL - PARA ÁTICO CONTABILIDADE,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 5,Unnamed: 7
0,MÊS,2016-09-01 00:00:00,NaN,NaN,NaN,NaN
1,DIA,RECEITA,DEPOSITANTE,DESPESAS,FAVORECIDO,SALDO
2,1,565.00,Doações,"2,000.00",Salário - Rosa Elisa - AGO/16,"4,480.23"
3,2,350.00,Doações,363.00,Ração - Agropecuaria 101,"4,467.23"
4,2,NaN,NaN,10.00,Combust.Posto S. Cristovão,"4,457.23"
5,2,NaN,NaN,143.57,Combust.Posto Shark,"4,313.66"
6,2,NaN,NaN,50.00,Saque no TAA,"4,263.66"
7,2,NaN,NaN,"4,260.00",Salário - Ieda Maria + Aliment,3.66
8,5,360.00,Doações,80.00,Combust.Auto PostoN.Camp.,283.66
9,5,NaN,NaN,12.90,Dupão - Alimentação,270.76
10,5,NaN,NaN,40.00,Saque no TAA,230.76
11,5,NaN,NaN,63.00,Tarifa bancária,167.76
12,6,140.00,Doações,269.00,Ração - Alexandre Pessoa,38.76
13,6,NaN,NaN,15.00,Combust.Posto Marquinho,23.76
14,8,440.00,Doações,20.00,Saque no TAA,443.76
15,9,120.00,NaN,413.00,Ração - Alexandre Pessoa,150.76
16,9,NaN,NaN,13.00,Medicamento-AlexandrePes,137.76
17,12,510.00,Doações,360.00,Ração - Alexandre Pessoa,287.76
18,12,NaN,NaN,100.00,Combust.Posto Camarão,187.76
19,12,NaN,NaN,100.00,Saque no TAA,87.76
20,12,NaN,NaN,82.50,Mariana Poeta,5.26
21,13,10.00,Doações,NaN,NaN,15.26
22,14,70.00,Doações,10.00,Saque no TAA,75.26
23,15,100.00,Doações,39.90,Ração - Agrop. S Bernardo,135.36
24,15,NaN,NaN,70.00,Saque no TAA,65.36
25,16,230.00,Doações,290.00,Mariana Poeta,5.36
26,19,170.00,Doações,100.00,Combust.Posto S. Cristovão,75.36
27,19,216.97,Cielo Vendas Débito,144.00,Ração - Alexandre Pessoa,148.33
28,19,NaN,NaN,120.00,Saque no TAA,28.33
29,20,250.00,Doações,140.00,Ração - Agropecuaria 101,138.33
30,20,"10,580.04",Auto Pista Litoral Sul,NaN,NaN,"10,718.37"
31,21,110.00,Doações,92.20,Ração - Agropecuaria DANDE,"10,736.17"
32,21,NaN,NaN,450.00,SaqueTAA-PgtoNotasPendent,"10,286.17"
33,21,NaN,NaN,"10,000.00",Clínica VeterináriaArgemiro,286.17
34,21,NaN,NaN,8.60,Tarifa TED acima,277.57
35,22,300.00,Doações,212.90,Ração - Agropecuaria 101,364.67
36,22,NaN,NaN,100.00,Saque no TAA,264.67
37,26,120.00,Doações,100.00,Combust. Alesat Auto Posto,284.67
38,26,NaN,NaN,200.00,SaqueTAA-PgtoNotasPendent,84.67
39,27,100.00,Doações,30.00,Combust. Posto Angeloni,154.67
40,27,NaN,NaN,15.00,Mônica Aparecida,139.67
41,28,40.00,Doações,100.00,Combust.Posto Shark,79.67
42,28,NaN,NaN,54.90,Arcadia,24.77
43,29,865.00,Doações,900.00,SaqueTAA-PgtoNotasPendent,- 10.23
44,29,"2,000.00",Empréstimo efetuado por:,440.00,DaianaMachado-MídiaSocial,"1,549.77"
45,29,NaN,Antônio Adulino martendal,8.60,Tarifa - TED acima,"1,541.17"
46,30,110.00,Doações,NaN,NaN,"1,651.17"
47,30,NaN,NaN,213.90,Ração - Agropecuaria 101,"1,437.27"
48,30,NaN,NaN,475.00,Banco Itaú - SLK PANDA-2ª P,962.27

In [2]:
month = df.iloc[0,1].month
year = df.iloc[0,1].year
data = str(year) + '-' + str(month) + '-' + '01'
df['data'] = pd.to_datetime(data)
df.drop(df.index[0:3], inplace = True)

In [3]:
df.columns = ['dia', 'receita', 'depositante', 'despesas', 'favorecido', 'saldo', 'data']
df = df[['receita', 'depositante', 'despesas', 'favorecido', 'data']]
df['filler1'] = '1'
df['filler2'] = '2'
df['filler3'] = '3'
df['filler4'] = '4'

C:\Users\Vanessa\AppData\Local\Temp\ipykernel_1700\2632990116.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['filler1'] = '1'

In [4]:
df

,receita,depositante,despesas,favorecido,data,filler1,filler2,filler3,filler4
3,350.00,Doações,363.00,Ração - Agropecuaria 101,2016-09-01,1,2,3,4
4,NaN,NaN,10.00,Combust.Posto S. Cristovão,2016-09-01,1,2,3,4
5,NaN,NaN,143.57,Combust.Posto Shark,2016-09-01,1,2,3,4
6,NaN,NaN,50.00,Saque no TAA,2016-09-01,1,2,3,4
7,NaN,NaN,"4,260.00",Salário - Ieda Maria + Aliment,2016-09-01,1,2,3,4
8,360.00,Doações,80.00,Combust.Auto PostoN.Camp.,2016-09-01,1,2,3,4
9,NaN,NaN,12.90,Dupão - Alimentação,2016-09-01,1,2,3,4
10,NaN,NaN,40.00,Saque no TAA,2016-09-01,1,2,3,4
11,NaN,NaN,63.00,Tarifa bancária,2016-09-01,1,2,3,4
12,140.00,Doações,269.00,Ração - Alexandre Pessoa,2016-09-01,1,2,3,4
13,NaN,NaN,15.00,Combust.Posto Marquinho,2016-09-01,1,2,3,4
14,440.00,Doações,20.00,Saque no TAA,2016-09-01,1,2,3,4
15,120.00,NaN,413.00,Ração - Alexandre Pessoa,2016-09-01,1,2,3,4
16,NaN,NaN,13.00,Medicamento-AlexandrePes,2016-09-01,1,2,3,4
17,510.00,Doações,360.00,Ração - Alexandre Pessoa,2016-09-01,1,2,3,4
18,NaN,NaN,100.00,Combust.Posto Camarão,2016-09-01,1,2,3,4
19,NaN,NaN,100.00,Saque no TAA,2016-09-01,1,2,3,4
20,NaN,NaN,82.50,Mariana Poeta,2016-09-01,1,2,3,4
21,10.00,Doações,NaN,NaN,2016-09-01,1,2,3,4
22,70.00,Doações,10.00,Saque no TAA,2016-09-01,1,2,3,4
23,100.00,Doações,39.90,Ração - Agrop. S Bernardo,2016-09-01,1,2,3,4
24,NaN,NaN,70.00,Saque no TAA,2016-09-01,1,2,3,4
25,230.00,Doações,290.00,Mariana Poeta,2016-09-01,1,2,3,4
26,170.00,Doações,100.00,Combust.Posto S. Cristovão,2016-09-01,1,2,3,4
27,216.97,Cielo Vendas Débito,144.00,Ração - Alexandre Pessoa,2016-09-01,1,2,3,4
28,NaN,NaN,120.00,Saque no TAA,2016-09-01,1,2,3,4
29,250.00,Doações,140.00,Ração - Agropecuaria 101,2016-09-01,1,2,3,4
30,"10,580.04",Auto Pista Litoral Sul,NaN,NaN,2016-09-01,1,2,3,4
31,110.00,Doações,92.20,Ração - Agropecuaria DANDE,2016-09-01,1,2,3,4
32,NaN,NaN,450.00,SaqueTAA-PgtoNotasPendent,2016-09-01,1,2,3,4
33,NaN,NaN,"10,000.00",Clínica VeterináriaArgemiro,2016-09-01,1,2,3,4
34,NaN,NaN,8.60,Tarifa TED acima,2016-09-01,1,2,3,4
35,300.00,Doações,212.90,Ração - Agropecuaria 101,2016-09-01,1,2,3,4
36,NaN,NaN,100.00,Saque no TAA,2016-09-01,1,2,3,4
37,120.00,Doações,100.00,Combust. Alesat Auto Posto,2016-09-01,1,2,3,4
38,NaN,NaN,200.00,SaqueTAA-PgtoNotasPendent,2016-09-01,1,2,3,4
39,100.00,Doações,30.00,Combust. Posto Angeloni,2016-09-01,1,2,3,4
40,NaN,NaN,15.00,Mônica Aparecida,2016-09-01,1,2,3,4
41,40.00,Doações,100.00,Combust.Posto Shark,2016-09-01,1,2,3,4
42,NaN,NaN,54.90,Arcadia,2016-09-01,1,2,3,4
43,865.00,Doações,900.00,SaqueTAA-PgtoNotasPendent,2016-09-01,1,2,3,4
44,"2,000.00",Empréstimo efetuado por:,440.00,DaianaMachado-MídiaSocial,2016-09-01,1,2,3,4
45,NaN,Antônio Adulino martendal,8.60,Tarifa - TED acima,2016-09-01,1,2,3,4
46,110.00,Doações,NaN,NaN,2016-09-01,1,2,3,4
47,NaN,NaN,213.90,Ração - Agropecuaria 101,2016-09-01,1,2,3,4
48,NaN,NaN,475.00,Banco Itaú - SLK PANDA-2ª P,2016-09-01,1,2,3,4